* ============================================================
* Encoding: UTF-8
* OpenMusE — Live music contribution to the economy (direct effect)
*
* PURPOSE
* This do-file estimates the *direct* contribution of live music to:
*  1) Total annual expenditure generated by attendance
*  2) Gross Value Added (GVA) contribution
*  3) Employment contribution (in FTE)
*
* INPUT FILES
*  (1) AV_EXPENDITURES_FROM_SURVEY.dta
*      - geo: country code
*      - product: product class (aligned with IO mapping)
*      - AV_EXPENDITURES: average expenditure per visit (currency as in survey)
*      - SOZA: Slovakia split (used to assign different attendance values)
*
*  (2) VA_EMP_COEFFICIENT.dta
*      - GVA_COEFFICIENT = B1G / P1  (value added per unit of output)
*      - EMP_COEFFICIENT = FTE / P1  (FTE per unit of output)
*      - valuesB1G: B1G in MIO_EUR (renamed to GVA_B1G)
*      - valuesP1 : P1  in MIO_EUR (renamed to OUTPUT_P1)
*
* KEY ASSUMPTIONS
*  - Attendance (num_visit_M) is provided externally and entered manually.
*  - Coefficients are applied linearly: expenditure * coefficient.
*  - Results are direct effects (no multipliers / indirect effects).
*
* OUTPUT
*  - LIVE_MUSIC_CONTRIBUTION.xls
* ============================================================


* ------------------------------------------------------------
* 0) Load survey-based expenditure data
* ------------------------------------------------------------
use "AV_EXPENDITURES_FROM_SURVEY.dta", clear


* ------------------------------------------------------------
* 1) Add attendance data (number of live-music visits, 2024)
*    Unit: MILLIONS of visits (num_visit_M)
*
*    NOTE: Values are hard-coded inputs (not from Eurostat).
* ------------------------------------------------------------
gen num_visit_M = .

replace num_visit_M = 31.2  if geo == "FR"
replace num_visit_M = 70    if geo == "DE"
replace num_visit_M = 29    if geo == "IT"
replace num_visit_M = 12.2  if geo == "PL"
replace num_visit_M = 28.3  if geo == "ES"

* Slovakia: split by SOZA flag (two alternative attendance figures)
replace num_visit_M = 1.42  if geo == "SK" & SOZA == 0
replace num_visit_M = 2.674 if geo == "SK" & SOZA == 1

* Hungary: manual adjustment (using aggregate value)
replace num_visit_M = 2     if geo == "HU"


* ------------------------------------------------------------
* 2) Compute total annual expenditure generated by live music
*
*    YEARLY_EXPENDITURE_M = num_visit_M * AV_EXPENDITURES
*    Interpretation: "total annual spending" associated with live music attendance.
* ------------------------------------------------------------
gen YEARLY_EXPENDITURE_M = num_visit_M * AV_EXPENDITURES


* ------------------------------------------------------------
* 3) Merge Input–Output coefficients to translate expenditure into:
*    - Value added (GVA)
*    - Employment (FTE)
*
*    Merge keys:
*      geo + product
* ------------------------------------------------------------
merge m:1 geo product using "VA_EMP_COEFFICIENT.dta"
drop _merge


* ------------------------------------------------------------
* 4) Value added contribution (direct)
*
*    GVA_COEFFICIENT = B1G / P1
*    VA_CONTRIBUTION = YEARLY_EXPENDITURE_M * GVA_COEFFICIENT
*
*    NOTE: This applies the IO-derived share of value added in output
*          to the expenditure total.
* ------------------------------------------------------------
gen VA_CONTRIBUTION = YEARLY_EXPENDITURE_M * GVA_COEFFICIENT

* Keep a clear naming for IO components
rename valuesB1G GVA_B1G
rename valuesP1  OUTPUT_P1


* ------------------------------------------------------------
* 5) Employment contribution (direct, in FTE)
*
*    EMP_COEFFICIENT = FTE / P1
*    EMP_CONTRIBUTION = YEARLY_EXPENDITURE_M * EMP_COEFFICIENT
* ------------------------------------------------------------
gen EMP_CONTRIBUTION = YEARLY_EXPENDITURE_M * EMP_COEFFICIENT


* ------------------------------------------------------------
* 6) Export results
* ------------------------------------------------------------
export excel using "LIVE_MUSIC_CONTRIBUTION.xls", firstrow(variables) replace
